server: 
  port: 3344 
  
spring:
  application:
    name:  microstarcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiKangLin/microstarcloud-config.git #GitHub上面的git仓库名字
 

