server:
  port: 9527

spring:
  application:
    name: microstarcloud-zuul-gateway



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

## 配置path，替换对应微服务的名称
zuul:
  #ignored-services: microstarcloud-dept
  prefix: /Lrunner
  ignored-services: "*"      #单个的可以用服务名，多个可以用*
  routes:
    mydept.serviceId: microstarcloud-dept
    mydept.path: /mydept/**

##此时的访问路径为http://myzuul.com:9527/Lrunner/mydept/dept/get/1

info:
  app.name: microcloud--zuul
  company.name: www.haha.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

